<?php
	session_start();
	if(isset($_SESSION['uname']))
	{
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Deer Park
Description: A two-column, fixed-width design for 1024x768 screen resolutions.
Version    : 1.0
Released   : 20090508

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>WATERMARK EMBEDDING</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>


<div id="header-wrapper">
	<div id="logo">
	<div style="position:absolute; left:358px; top:177px">
      <h3>For hiding confidentials</h3>   </div>  
	        
  </div>
    
<hr />
	<!-- end #logo -->
	<div id="header">
		<div id="menu">
			<ul>
				<li><a href="insertbranch.php">New Branch</a></li>
				<li><a href="staffdet.php">New Staff</a></li>
				<li><a href="userconfig.php">User Configuration</a></li>
				<li><a href="sendmsg.php">Send Message</a></li>
				<li><a href="receivemsg.php">Receive Message</a></li>
				<li><a href="logout.php" target="_top">Logout</a></li>
			</ul>
		</div>
		<!-- end #menu -->
		
		<!-- end #search -->
	</div>
	<!-- end #header -->
</div>
<!-- end #header-wrapper -->

<div id="page">
	<div id="content">
		<div class="post">


		
<h2 class="title"> About WATERMARK</h2>
		  <p class="date"></p>
			<p class="meta"><em>Perception For Hiding confidentials and Find pirated data</p>
			<div class="entry">
				<img src="images/p1.jpeg"/><p>Digital watermarking is closely related to steganography. Watermarking is the process of embedding hidden information which is only visible after a process has been carried out. An example is the watermarking of bank notes to prove legitimacy, whereupon holding the note to the light produces a visible image, the watermark. The main differences between watermarking and steganography is that in watermarking, the information hidden relates to the object it is hidden in. </p>
				<p class="links"><a href="#" class="comments">Comments (64)</a> &nbsp;&nbsp;&nbsp; <a href="#" class="permalink">Full article</a></p>
			</div>
		</div>
		<div class="post">
			<h2 class="title">About Us</h2>
			<p class="date">01.23.09</p>
			<p class="meta"><em>Posted by <a href="#">admin</a> on March 8, 2008</em></p>
			<div class="entry">
				<p>By this Perception,Store branch details and working staff details under particular branch. Only Authorised Members are allowed to share their confidentials. For Each hiding detail, two keys are generated. one of the key is generated by authority and another one is auto generated private key. So Destiny Authority will answer for those two keys to see the message. Whenever see the message u may also see the trace of the department logo(ie., watermark)
                
                In Future,using this watermark find the information is send by which department officials...                
                
                </p>
				<p class="links"><a href="#" class="comments">Comments (64)</a> &nbsp;&nbsp;&nbsp; <a href="#" class="permalink">Full article</a></p>
			</div>
		</div>
	</div>
	<!-- end #content -->
	<div id="sidebar">
		<ul>
			<li><br />
				    <center><img src="images/p2.jpeg" width="120"/></li></center>
			<li id="calendar">
				<h2>Calendar</h2>
				<div id="calendar_wrap">
					<table align="center" summary="Calendar">
						<caption>
						May 2013
						</caption>
						<thead>
							<tr>
								<th abbr="Monday" scope="col" title="Monday">M</th>
								<th abbr="Tuesday" scope="col" title="Tuesday">T</th>
								<th abbr="Wednesday" scope="col" title="Wednesday">W</th>
								<th abbr="Thursday" scope="col" title="Thursday">T</th>
								<th abbr="Friday" scope="col" title="Friday">F</th>
								<th abbr="Saturday" scope="col" title="Saturday">S</th>
								<th abbr="Sunday" scope="col" title="Sunday">S</th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td abbr="February" colspan="3" id="prev"><a href="#" title="">&laquo; April </a></td>
								<td class="pad">&nbsp;</td>
								<td abbr="April" colspan="3" id="next"><a href="#" title="">June &raquo;</a></td>
							</tr>
						</tfoot>
						<tbody>
							<tr>
								<td colspan="5" class="pad">&nbsp;</td>
								<td>1</td>
								<td>2</td>
							</tr>
							<tr>
								<td>3</td>
								<td>4</td>
								<td>5</td>
								<td>6</td>
								<td>7</td>
								<td>8</td>
								<td>9</td>
							</tr>
							<tr>
								<td>10</td>
								<td id="today">11</td>
								<td>12</td>
								<td>13</td>
								<td>14</td>
								<td>15</td>
								<td>16</td>
							</tr>
							<tr>
								<td>17</td>
								<td>18</td>
								<td>19</td>
								<td>20</td>
								<td>21</td>
								<td>22</td>
								<td>23</td>
							</tr>
							<tr>
								<td>24</td>
								<td>25</td>
								<td>26</td>
								<td>27</td>
								<td>28</td>
								<td>29</td>
								<td>30</td>
							</tr>
							<tr>
								<td>31</td>
								<td class="pad" colspan="6">&nbsp;</td>
							</tr>
						</tbody>
					</table>
				</div>
			</li>
			<li>
				<h2>Links</h2>
				<ul>
					<li><a href="insertbranch.php" target="a">New Branch</a></li>
		<li><a href="staffdet.php" target="a">New Staff</a></li>
		<li><a href="userconfig.php" target="a">User Configuration</a></li>
		<li><a href="sendmsg.php" target="a">Send Message</a></li>
		<li><a href="receivemsg.php" target="a">Receive Message</a></li>
		<li><a href="logout.php" target="_top">Logout</a></li>
					
				</ul>
			</li>
		</ul>
  </div>
<!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>
</div>
<!-- end #page -->

<div id="footer">
	<p>Copyright (c) 2008 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org">FCT</a>.</p>
</div>
<!-- end #footer -->
</body>
</html>

<?php
	}
	else
	echo "<font color='blue' size='5'>Page Cannot be displayed...</font>";
?>